### ISSUE TITLE
Adapter doesn't respect scopes

### ISSUE THREAD

**Issue by computerwizjared** [vzakharchenko/keycloak-lambda-authorizer#43]
In `umaConfiguration.js` `matchResource` method, it will return a resource whether or not the current user has the scope that is being requested. I would expect that if the user does not have the scope specified in the resource enforcement object (like below), it would return an access is denied error.

```
enforce: {
  enabled: true,
  resource: {
    uri: '/customer',
    scope: 'POST',
    matchingUri: true
  },
}
```

Why is this not using the authorization request documented here? https://www.keycloak.org/docs/latest/authorization_services/#_service_obtaining_permissions

**Comment by vzakharchenko** [comment]
@computerwizjared, here is authorization request: https://github.com/vzakharchenko/keycloak-lambda-authorizer/blob/7f64e1564ef0c252956de73c221635ddf1cc4153/src/umaConfiguration.js#L58 and https://github.com/vzakharchenko/keycloak-lambda-authorizer/blob/7f64e1564ef0c252956de73c221635ddf1cc4153/src/clientAuthorization.js#L68

The idea is If JWT token does not have authorization part in payload than adapter use "authorization request". In this case adapter has ability work with access_token as well as entitlement token .

About Scope:
Exactly is how it work, if the user does not have scope for the resource then it will return a rejected error.

The adapter ask keycloak to get resource with scope,   uri, matchingUri, owner, type and uses that resource in ```matchResource```. This way add ability to use entitlement token without resource names(parameter ```response_include_resource_name``` ) 
https://github.com/vzakharchenko/keycloak-lambda-authorizer/blob/7f64e1564ef0c252956de73c221635ddf1cc4153/src/umaConfiguration.js#L27

**Comment by computerwizjared** [comment]
@vzakharchenko thank you so much for the explanation! That helps me a lot and I've now learned about the RPT and how that works. I wasn't super familiar with it before.

However, I don't think the scope checks are working properly. It seems to be granting me access as long as a scope is assigned to a resource, and does not actually check if the RPT contains the scope needed. Do you have an idea of where this change should be made? I'm looking around to see if I can find it.
